apiVersion: v1
kind: Service
metadata:
  name: whale-svc
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: "whale-consul-service"
    consul.hashicorp.com/service-tags: "whale-svc,k8s-service"
    consul.hashicorp.com/service-port: "http"
  labels:
    app: whale-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 32000
    protocol: TCP
  selector:
    app: whale-app
