apiVersion: apps/v1
kind: Deployment
metadata:
  name: whale-deploy
  labels:
    app: whale-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whale-app
  template:
    metadata:
      labels:
        app: whale-app
    spec:
      containers:
      - image: dstefansky/whale-app:latest
        name: whale-pod
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        - containerPort: 5001
          name: metrics
          protocol: TCP
