---
- hosts: grafanaservers
  roles:
    - role: grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin
        grafana_datasources:
          - name: "Prometheus"
            type: "prometheus"
            access: "proxy"
            url: "http://54.226.179.166:9090"
            basicAuth: false